import type { Metadata } from "next";
import {  Space_Grotesk, Montserrat, BioRhyme } from "next/font/google";
import "./globals.css";
export const dynamic = "force-dynamic"; 
import SmoothScroll from "./components/addons/SmoothScroll";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased bg-black`}
      >
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}
